"""agregando tabla de alumnos.

Revision ID: 302a05ccf636
Revises: 583677b9f761
Create Date: 2024-10-19 14:09:27.831508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302a05ccf636'
down_revision = '583677b9f761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumnos')
    # ### end Alembic commands ###
