"""agregando Grados y Clases.

Revision ID: 583677b9f761
Revises: b5348573ff01
Create Date: 2024-10-19 13:58:54.323936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583677b9f761'
down_revision = 'b5348573ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('maestro_id', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['maestro_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clases')
    op.drop_table('grados')
    # ### end Alembic commands ###
